language: php
sudo: false

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=29

matrix:
  fast_finish: true
  include:
    - php: 7.1.18
    - php: 7.2
    - php: 7.3

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer install

script:
  -  ./vendor/bin/phpunit -c ./phpunit.xml
  - ./bin/console lint:yaml config
